[project]
name = "advent-of-code"
version = "0.1.0"
description = "Advent of Code attempts"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "pytest>=9.0.1",
]

[tool.uv.workspace]
members = [
    "2025",
]
